name: Automated Multi Branch workflow

on:
  push:
    branches:
      - main
      - stage
      - prod

# now the jobs
jobs:
  get_branch:
    name: Get the branch that triggered the event
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
      # steps.[step_id].outputs.[output_name]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # now look for a way to know which branch triggered the push event
      - name: Get the branch that triggered the push
        id: extract_branch
        # ::set-output
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          # now push the output so another job can use it
          # deprecated due to security issues
          # echo "::set-output name=branch::${BRANCH_NAME}"
          # better way of doing things
            echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo $BRANCH_NAME
        # the jobs will only run if they match the need condition
  prod_condition:
    needs: 
      - get_branch
    name: Production trigger workflow
    # env:
    #   BRANCH: ${{ needs.get_branch.outputs.branch }}
    # this will run the production workflow
    if: needs.get_branch.outputs.branch == 'prod'
    uses: './.github/workflows/prod.yml'
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3
    #   - name: Calling the production workflow
    #     uses: 'tim18fak-sys/-Multiple-GitHub-Actions-Workflow-/.github/workflows/prod.yml@main'
        # run: |
        #   echo "Running production workflow"
          
  stage_condition:
    needs: 
      - get_branch
    name: Stage Trigger workflow
    if: needs.get_branch.outputs.branch == 'stage'
    uses: './.github/workflows/stage.yml'
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3
    #   - name: Calling the stage workflow
    #     uses: 'tim18fak-sys/-Multiple-GitHub-Actions-Workflow-/.github/workflows/stage.yml@main'
        # run: |
        #   echo "Running stage workflow"
  dev_condition:
    needs: 
      - get_branch
    name: Dev Trigger workflow
    if: needs.get_branch.outputs.branch == 'main'
    uses: './.github/workflows/dev.yml'
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3
    #   - name: Calling the dev workflow
    #     uses: 'tim18fak-sys/-Multiple-GitHub-Actions-Workflow-/.github/workflows/dev.yml@main'
        # run: |
        #   echo "Running dev workflow"


  
  # multi_auto:
  #   needs:
  #   - get_branch
  #   name: This will trigger the different workflows
  #   runs-on: ubuntu-latest
  #   env:
  #   # this is to pass in the out get_branch job
  #     BRANCH: ${{ needs.get_branch.outputs.branch }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Check the output of the env file
  #       run: |
  #         echo $BRANCH || "Nothing"
        # now d
